### ISSUE TITLE
你好，这个模型的结果怎样？

### ISSUE THREAD

**Issue by zuowanbushiwo** [WWWWWLI/Spoofing-Detection#1]
你好
      我现在做声纹项目，需要一个PA的做前端，对您这个项目很感兴趣，请问你这个模型的结果怎么样？ 
      和这篇文章 [REPLAY AND SYNTHETIC SPEECH DETECTION WITH RES2NET ARCHITECTURE](https://arxiv.org/abs/2010.15006)结果有区别吗？谢谢！
![image](https://user-images.githubusercontent.com/3354428/217515248-d1080ed5-57f2-403b-875b-924f82a0e416.png)

**Comment by WWWWWLI** [comment]
你好
我是在ASVSpoof2021上测试，结果min-tDCF=0.9647，EER=40.15%，没有在ASVSpoof2019的数据集上测试

**Comment by zuowanbushiwo** [comment]
这么大差距啊？ASVSpoof2021的数据集难度要高很多吗？

**Comment by WWWWWLI** [comment]
是的，差距很大，具体可以参考ASVSpoof2021和ASVSpoof2019比赛结束后官方发布的paper
我认为还有一部分原因是由于2021比赛上，规则是仅可以采用2019的数据进行训练
我认为你也可以将2021数据集的一部分划分为训练集，查看模型是否会有性能提升，当然，为了公平比较，其他的参赛模型也需要同样的数据划分来训练

**Comment by zuowanbushiwo** [comment]
好的，非常感谢回复 。你看2019的PA 结果 比2021的PA 结果快相差了大几十倍，但是他们的训练数据都是一样，都是2019的，只是测试数据不一样。2019的训练数据和测试数据都是仿真的，所以2019的结果非常好。但是2021的测试数据是真实设备的录制播放，这样train 和 test的数据就不一样了，所以用2019的trian数据跑2021的test数据非常差，是不是这样？请教一下，除了ASV数据集外，还有有没有真实的PA数据集？我是做demo，不是研究，也不比赛，只是想提升demo的效果。

**Comment by zuowanbushiwo** [comment]
![image](https://user-images.githubusercontent.com/3354428/217701397-4bbc3f6b-ca78-4568-9a72-6ebbf816dbc7.png)

还请问一下，这个截图的前几名的团队的文章有吗？特别是前三名的。我搜索了一下，没搜索到。谢谢！

**Comment by zuowanbushiwo** [comment]
感谢指导  
你的HFCS 是没有完成吗？ 我看没有达到 Robust Cross-SubBand Countermeasure Against Replay Attacks 论文中的的效果？
要用2019的train 数据集上在2021 的test数据集上有好效果，是不是数据扩增/增强 很重要了？这个你有什么研究和方法吗？
谢谢！

**Comment by WWWWWLI** [comment]
整理的模型结构完成了，但是有些trick可能与原文不同，因此没有达到与原文相同的结果
具体的细节你可以参考原文，另外我也建议你尝试第一名的模型，效果还是很不错的

**Comment by zuowanbushiwo** [comment]
你好，感谢回复。第一名的模型你实现了吗？会上传到你这个仓库吗？

**Comment by WWWWWLI** [comment]
有实现，eer约为29%，min-tDCF=0.8，这个因为近期比较忙，而且跟当前的训练框架不同，所以没打算上传到这个仓库
你如果有需求自行按照文章中的超参数设置就可以，文章写的比较详细

**Comment by zuowanbushiwo** [comment]
好的，感谢！
